title: Curriculo - Ana Clara Martins Batista
email: anaclaramartinsbatista2006@gmail.com
description: Curriculo profissional e portfolio de Ana Clara Martins Batista.
baseurl: "/ds881-curriculo-GRR20246205"
url: "https://anambclara.github.io/"
github_username: anambclara

destination: _site
