title: "Currículo - Ana Clara Martins Batista"
email: "anaclaramartinsbatista2006@gmail.com"
description: "Currículo profissional de Ana Clara Martins Batista, desenvolvedora de software."
lang: "pt-BR"
url: "https://anambclara.github.io"
baseurl: "/ds881-curriculo-GRR20246205"

exclude:
  - Dockerfile
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - tests
  - vendor
